# Dependencies
markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
baseurl:

title:		Code By Codes
tagline:	'Personal blog from Cody Norman'
description:	'Rants a musings from a Ruby developer in Philadelphia.'
url:		http://codebycodes.com
commentsystem:	google
disqus:		example

author:
  name:		'Cody Norman'
  url:		https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon:		/assets/images/logo.png
cover:		/assets/images/footer_lodyas.png

social:
  - icon:	twitter
    url:	https://twitter.com/cnorm35
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/cnorm35
    desc:	Fork me on github


menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

  - title:  Blog
    url:  /blog

copyright:
  author:	Cody Norman
  url:		http://codebycodes.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
